### ISSUE TITLE
Small console spam

### ISSUE THREAD

**Issue by crunkazcanbe** [aksource/PotionExtension#1]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer transform
INFO: Start transforming PotionEffect Class
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomVisitor visitMethod
INFO: Transforming getPotionID method
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor3 visitFieldInsn
INFO: getPotionID:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomVisitor visitMethod
INFO: Transforming onUpdate method
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor1 visitFieldInsn
INFO: onUpdate:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomVisitor visitMethod
INFO: Transforming readCustomPotionEffectFromNBT method
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor2 visitMethodInsn
INFO: readCustomPotionEffectFromNBT:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor2 visitMethodInsn
INFO: readCustomPotionEffectFromNBT:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor2 visitMethodInsn
INFO: readCustomPotionEffectFromNBT:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer$CustomMethodVisitor2 visitMethodInsn
INFO: readCustomPotionEffectFromNBT:change id in [0 - 255]
Feb 18, 2015 7:48:59 PM ak.potionextension.asm.PotionEffectTransformer transform
INFO: Finish transforming PotionEffect Class

Thanx -Crunk

**Comment by aksource** [comment]
I will fix it in 1.0.5.
